### ISSUE TITLE
No Contributing guidelines 

### ISSUE THREAD

**Issue by SRADHA-SURESH12** [Niravprajapati1/News-website#5]
### What happened?

A set of contributing guidelines is required.

### What did you expect to happen?

While looking for how to contribute to the repository, I couldn't find any guidelines.

### How can we reproduce it (as minimally and precisely as possible)?

Using MIT opensource guidelines.

**Comment by Niravprajapati1** [comment]
Thanks for suggestion 😊

**Comment by Niravprajapati1** [comment]
Can you make a pr for this ?
